# Documentation available at https://expeditor.chef.io/docs/getting-started/

# The name of the product keys for this product (from mixlib-install)
product_key:
  - chef

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-infra-notify

# Which Ruby Gems, built when the Omnibus package is built, to publish to rubygems.org
# This publish is triggered by the `built_in:publish_rubygems` artifact_action.
rubygems:
  - chef
  - chef-config

docker_images:
  - chef

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true
  # The tag format to use (e.g. v1.0.0)
  version_tag_format: "v{{version}}"
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # allow bumping the major release via label
  major_bump_labels:
    - "Expeditor: Bump Version Major"

# Which Github branches to build Omnibus releases from, and what versions
# (as determined by the value in the VERSION file) those branches are responsible
# for building.
release_branches:
  - master:
      version_constraint: 15*
  - chef-14:
      version_constraint: 14*

changelog:
  rollup_header: Changes not yet released to stable

subscriptions:
  - workload: artifact_published:unstable:chef:{{version_constraint}}
    actions:
      - built_in:build_docker_image
  - workload: artifact_published:current:chef:{{version_constraint}}
    actions:
      - built_in:tag_docker_image
      - built_in:promote_habitat_packages
  - workload: artifact_published:stable:chef:{{version_constraint}}
    actions:
      - built_in:rollover_changelog
      - bash:.expeditor/update_dockerfile.sh@chef/chef@master
      - built_in:tag_docker_image
      - built_in:promote_habitat_packages
      - built_in:publish_rubygems
      - built_in:notify_chefio_slack_channels
  # These actions are taken, in order they are specified, anytime a Pull Request is merged.
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Expeditor: Skip Version Bump"
            - "Expeditor: Skip All"
      - bash:.expeditor/update_version.sh:
          only_if: built_in:bump_version
      - built_in:update_changelog:
          ignore_labels:
            - "Expeditor: Skip Changelog"
            - "Expeditor: Skip All"
