# Documentation available at https://expeditor.chef.io/docs/getting-started/

# the name we use for this project when interacting with expeditor chatbot
project:
  alias: chef-13

# The name of the product keys for this product (from mixlib-install)
product_key:
  - chef

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-notify

# Which Ruby Gems, built when the Omnibus package is built, to publish to rubygems.org
# This publish is triggered by the `built_in:publish_rubygems` artifact_action.
rubygems:
  - chef
  - chef-config

docker_images:
  - chef

github:
  # cleanup PR branches post merge
  delete_branch_on_merge: true
  # The file where the MAJOR.MINOR.PATCH version is kept. The version in this file
  # is bumped automatically via the `built_in:bump_version` merge_action.
  version_file: "VERSION"
  # The file where our CHANGELOG is kept. This file is updated automatically with
  # details from the Pull Request via the `built_in:update_changelog` merge_action.
  changelog_file: "CHANGELOG.md"
  # This will trigger an Omnibus build with EXPIRE_CACHE enabled after
  # a pull request is merged into the release branch.
  enable_expire_cache: true
  # The tag format to use (e.g. v1.0.0)
  version_tag_format: "v{{version}}"
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Minor Version"

# Which Github branches to build Omnibus releases from, and what versions
# (as determined by the value in the VERSION file) those branches are responsible
# for building.
release_branches:
  - master:
      version_constraint: 15*
  - chef-14:
      version_constraint: 14*
  - chef-13:
      version_constraint: 13*

subscriptions:
  - workload: artifact_published:unstable:chef:{{version_constraint}}
    actions:
      - built_in:build_docker_image
  - workload: artifact_published:current:chef:{{version_constraint}}
    actions:
      - built_in:tag_docker_image
  - workload: artifact_published:stable:chef:{{version_constraint}}
    actions:
      - built_in:rollover_changelog
      - bash:.expeditor/update_dockerfile.sh@chef/chef@master
      - built_in:tag_docker_image
      - built_in:publish_rubygems
      - built_in:notify_chefio_slack_channels
  # These actions are taken, in order they are specified, anytime a PR is merged.
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Expeditor: Skip Version Bump"
            - "Expeditor: Skip All"
      - bash:.expeditor/update_version.sh@chef/chef@master:
          only_if: built_in:bump_version
      - built_in:update_changelog:
          ignore_labels:
            - "Expeditor: Exclude From Changelog"
            - "Expeditor: Skip All"
      - built_in:trigger_omnibus_release_build:
          ignore_labels:
            - "Expeditor: Skip Build"
            - "Expeditor: Skip All"
          only_if: built_in:bump_version
