---
name: spellcheck

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: carlosperate/download-file-action@v1.0.3
        id: download-custom-dictionary
        with:
          file-url: 'https://raw.githubusercontent.com/chef/chef_dictionary/master/chef.txt'
          file-name: 'chef_dictionary.txt'
      - uses: zwaldowski/cspell-action@v1
        with:
          config: cspell.json
          paths: "**/*"
